dist: xenial

language: python
python:
  - '3.7'
  - '3.6'
install:
script: python setup.py test

env:
  global:
    - OMP_NUM_THREADS=4

addons:
  apt:
    packages:
      - libbz2-dev
      - liblzma-dev
      - zlib1g-dev
